language: node_js
addons:
  ssh_known_hosts:
    - quasar.cross-solution.de
node_js:
  - "10.18.1"
cache:
  directories:
    - node_modules
    - "$HOME/.composer/cache"
    - "$HOME/.yarn"
matrix:
  fast_finish: true
  include:
    - php: "7.2"
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_e989228ec430_key -iv $encrypted_e989228ec430_iv
    -in .travis/deploy.enc -out ~/.ssh/id_ed25519 -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ~/.ssh/id_ed25519
  - ssh-add ~/.ssh/id_ed25519
  - chmod +x deployer.phar
install:
  - yarn
  - node_modules/.bin/quasar build -m ssr
script:
  - node_modules/.bin/quasar test --unit jest
deploy:
  - provider: script
    skip_cleanup: true
    script: "./deployer.phar deploy"
    on:
      branch: master
